package models

// Generated by niuhe.idl

// 如要同步表结构, 需要手动将 Config 手动添加到 models.go 文件的 GetSyncModels 数组中

import (
	"fmt"

	"github.com/ma-guo/admin-core/app/v1/protos"

	"time"
)

// 文章-内容管理
type SysDocument struct {
	Id       int64     `xorm:"NOT NULL PK AUTOINCR INT(11)"`
	Name     string    `xorm:"VARCHAR(255) COMMENT('名称')"` // 名称
	Markdown string    `xorm:"TEXT COMMENT('markdown内容')"` // markdown内容
	Html     string    `xorm:"TEXT COMMENT('html内容')"`     // html内容
	CreateAt time.Time `xorm:"created"`                    // 创建时间
	UpdateAt time.Time `xorm:"updated"`                    // 更新时间
	DeleteAt time.Time `xorm:"deleted"`                    // 删除时间
}

type SysDraft struct {
	Id       int64     `xorm:"NOT NULL PK AUTOINCR INT(11)"`
	DocId    int64     `xorm:"INT(11) COMMENT('文章id')"`    // 文章id
	Name     string    `xorm:"VARCHAR(255) COMMENT('名称')"` // 名称
	Markdown string    `xorm:"TEXT COMMENT('markdown内容')"` // markdown内容
	Version  int       `xorm:"INT(11) COMMENT('版本号')"`     // 版本号
	CreateAt time.Time `xorm:"created"`                    // 创建时间
	UpdateAt time.Time `xorm:"updated"`                    // 更新时间
	DeleteAt time.Time `xorm:"deleted"`                    // 删除时间
}

func (row *SysDocument) ToProto(item *protos.DocumentItem, host string) *protos.DocumentItem {
	if item == nil {
		item = &protos.DocumentItem{}
	}
	item.Id = row.Id
	item.Name = row.Name
	item.Markdown = row.Markdown
	item.Html = row.Html
	item.Url = buildDocumentUrl(host, row.Id)
	item.CreateAt = row.CreateAt.Format(time.DateTime)
	item.UpdateAt = row.UpdateAt.Format(time.DateTime)
	return item
}

func (row *SysDraft) ToProto(item *protos.DocumentItem, host string) *protos.DocumentItem {
	if item == nil {
		item = &protos.DocumentItem{}
	}
	item.Id = row.Id
	item.Name = row.Name
	item.Markdown = row.Markdown
	item.Version = row.Version
	item.Url = buildDocumentUrl(host, row.Id)
	item.CreateAt = row.CreateAt.Format(time.DateTime)
	item.UpdateAt = row.UpdateAt.Format(time.DateTime)
	return item
}
func buildDocumentUrl(host string, id int64) string {
	return fmt.Sprintf("%v/web/document/article/?id=%v", host, id)
}
