package protos

import (
	"github.com/ma-guo/niuhe"
)

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改, 不需要生成本文件时请在 langs 中移除 route 配置

// web 模块下的所有路由数组
var RouteItems = []*niuhe.RouteItem{
	{Method: "GET", Path: "/web/document/article/", Name: "获取文章详情"},
}
