package protos

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

// 获取文章详情请求参数
type DocumentArticleReqMsg struct {
	Id     int64 `json:"id" zpf_name:"id" zpf_reqd:"true" zpf_minnum:"1"` //	文章ID 最小值:1
	Single bool  `json:"single" zpf_name:"single"`                        //	是否单页
	Html   bool  `json:"html" zpf_name:"html"`                            //	是否直接返回HTML内容
}

// 获取文章详情返回参数
type DocumentArticleRspMsg struct {
}
