package views

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import (
	"github.com/ma-guo/admin-core/app/v1/protos"

	"github.com/ma-guo/niuhe"
)

type _Gen_Document struct{}

// 分页查询获取内容管理信息
func (v *_Gen_Document) Page_GET(c *niuhe.Context, req *protos.DocumentPageReq, rsp *protos.DocumentPageRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 分页查询草稿信息
func (v *_Gen_Document) DraftPage_GET(c *niuhe.Context, req *protos.DocumentDragePageReq, rsp *protos.DocumentPageRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 查询获取内容管理信息
func (v *_Gen_Document) Form_GET(c *niuhe.Context, req *protos.DocumentFormReq, rsp *protos.DocumentItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 添加内容管理信息
func (v *_Gen_Document) Add_POST(c *niuhe.Context, req *protos.DocumentItem, rsp *protos.DocumentItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 更新内容管理信息
func (v *_Gen_Document) Update_POST(c *niuhe.Context, req *protos.DocumentItem, rsp *protos.DocumentItem) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}

// 删除内容管理信息
func (v *_Gen_Document) Delete_DELETE(c *niuhe.Context, req *protos.DocumentDeleteReq, rsp *protos.DocumentNoneRsp) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
