package views

// Generated by niuhe.idl

import (
	"fmt"
	"net/http"

	"github.com/ma-guo/admin-core/app/web/protos"
	"github.com/ma-guo/admin-core/xorm/services"

	"github.com/flosch/pongo2"
	"github.com/ma-guo/niuhe"
)

type Document struct {
	_Gen_Document
}

// 获取文章详情
func (v *Document) Article_GET(c *niuhe.Context, req *protos.DocumentArticleReqMsg, rsp *protos.DocumentArticleRspMsg) error {
	c.IgnoreResult()

	svc := services.NewSvc()
	defer svc.Close()
	doc, has, err := svc.SysDocument().GetById(req.Id)
	if err != nil {
		c.String(http.StatusOK, fmt.Sprintf("%v", err))
		return nil
	}
	if !has {
		c.String(http.StatusOK, "文章不存在")
		return nil
	}
	if req.Html {
		c.String(http.StatusOK, doc.Html)
		return nil
	}
	if req.Single {
		c.HTML(http.StatusOK, "doc-single.html", pongo2.Context{
			"html":  doc.Html,
			"title": doc.Name,
		})
	} else {
		c.HTML(http.StatusOK, "doc.html", pongo2.Context{
			"html":  doc.Html,
			"title": doc.Name,
		})
	}
	return nil
}
func init() {
	GetModule().Register(&Document{})
}
