package views

// Generated by niuhe.idl
// 此文件由 niuhe.idl 自动生成, 请勿手动修改

import (
	"github.com/ma-guo/admin-core/app/web/protos"

	"github.com/ma-guo/niuhe"
)

type _Gen_Document struct{}

// 获取文章详情
func (v *_Gen_Document) Article_GET(c *niuhe.Context, req *protos.DocumentArticleReqMsg, rsp *protos.DocumentArticleRspMsg) error {
	return niuhe.NewCommError(-1, "Not Implemented")
}
