package views

// Generated by niuhe.idl
import (
	"github.com/ma-guo/niuhe"
)

var thisModule *niuhe.Module

func GetModule() *niuhe.Module {
	if thisModule == nil {
		thisModule = niuhe.NewModule("web")
		// 需要在 .config.json5 中添加 langs: ["route"]
		// 使用下面的代码, 当错误码同 RPC 方式定义的 .codes(...) 不同时回收到回调
		// thisModule.AddRouteItem(protos.RouteItems...)
		// thisModule.RegisterCodeNotify(func(code int, path string) {
		// 	niuhe.LogError("code: %v with %v", code, path)
		// })
	}
	return thisModule
}
